name: deploy_web_server
on:
  push:
    branches:
      - main

jobs:
  deploy_web_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build web server
        run: docker compose build alexdr-house-predict

      - name: Login into docker
        run: echo "${{ secrets.LOGIN_SECRET }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag web server
        run: docker tag alexandredr/alexdr-house-predict alexandredr/alexdr-house-predict:latest

      - name: Push docker image
        run: docker push alexandredr/alexdr-house-predict

      - name: Copy docker-compose file to server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SERVER_LOGIN }}" "mkdir -p ~/adr"
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no docker-compose.yml "${{ secrets.SERVER_LOGIN }}":~/adr/docker-compose.yml

      - name: Connect and pull image
        run: sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SERVER_LOGIN }}" "cd ~/adr && docker pull alexandredr/alexdr-house-predict:latest"

      - name: Restart the container
        run: sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SERVER_LOGIN }}" "cd ~/adr && docker compose down && docker compose up -d alexdr-house-predict"